title: UHM Lost and Found
description: A web application dedicated to posting lost and found items for the University of Hawaii Manoa campus.
google_analytics:
theme: jekyll-theme-tactile
gems:
  - jekyll-mentions
